#!/usr/bin/python -tt
# -*- coding: UTF-8 -*-
# vim: ts=4 sw=4 et ai si

"""
OPML generator for Google Reader
"""

__author__ = "Andy Shevchenko <andy.shevchenko@gmail.com>"
__version__ = "0.1.0"
__license__ = "GPLv2"

import os
import sys
import logging
import netrc
from optparse import OptionParser
import operator
import urllib2
import urllib
from xml.etree import cElementTree as ElementTree

import gdata.youtube.service
import gdata.photos.service

LOG = logging.getLogger(os.path.basename(sys.argv[0]))

class OPMLGenError(Exception):
    """ Custom Exception class """
    pass

def get_auth_data(host):
    """ Return login, account and password tuple for given host if found """
    try:
        dotnetrc = netrc.netrc()
    except (IOError, netrc.NetrcParseError), err:
        raise OPMLGenError("Can't read ~/.netrc file: %s" % str(err))
    return dotnetrc.authenticators(host)

class Service(object):
    """ Virtual base class for services """
    def __init__(self):
        self.name = self.__class__.__name__
        self.host = None
        self.ownfeed = False

    def login(self):
        """ Login to service """
        try:
            login, _, passwd = get_auth_data(self.host)
        except TypeError:
            raise OPMLGenError("Can't get auth data for host '%s'" % self.host)

        try:
            self._login(login, passwd)
        except AttributeError:
            raise OPMLGenError("Login method is undefined")

    def opml(self, ownfeed=False):
        """ Login to service and generate OPML """
        self.login()
        self.ownfeed = ownfeed
        try:
            return self._opml()
        except AttributeError:
            raise OPMLGenError("OPML generator for service '%s' is undefined" %
                    self.name)

class LiveJournalService(Service):
    """ Class for LiveJournal service """
    def __init__(self):
        self.host = "www.livejournal.com"
        self.url = None

    def _login(self, login, passwd):
        self.url = "http://%s/tools/opml.bml?user=%s" % (self.host, login)

    def _opml(self):
        ufd = urllib2.urlopen(self.url)
        root = ElementTree.parse(ufd)
        for elem in root.findall('body/outline'):
            yield elem.get('text'), elem.get('xmlURL')

class YouTubeService(Service):
    """ Class for YouTube service """
    def __init__(self):
        self.host = "www.youtube.com"
        self.client = gdata.youtube.service.YouTubeService()

    def _login(self, login, passwd):
        self.client.ClientLogin(login, passwd)

    def _opml(self):
        feed = self.client.GetYouTubeSubscriptionFeed()
        for entry in feed.entry:
            if entry.GetSubscriptionType() == 'channel':
                href = entry.feed_link[0].href.replace('api', 'base')
                yield entry.title.text, href
        if self.ownfeed:
            text = feed.title.text.replace("Subscriptions of",
                    "Videos published by :")
            href = feed.GetFeedLink().href.replace('api', 'base')
            yield text, href.replace('/contacts', '').replace('subscriptions',
                    'uploads')

class PicasaWebService(Service):
    """ Class for PicasaWeb service """
    def __init__(self):
        self.host = "picasaweb.google.com"
        self.client = gdata.photos.service.PhotosService()

    def _login(self, login, passwd):
        self.client.ClientLogin(login, passwd)

    def _opml(self):
        feed = self.client.GetContacts()
        for entry in feed.entry:
            href = entry.GetFeedLink().href.replace('api', 'base')
            yield entry.title.text, href
        if self.ownfeed:
            text = feed.title.text
            href = feed.GetFeedLink().href
            yield text, href.replace('api', 'base').replace('/contacts', '')

class GoogleReader(gdata.service.GDataService):
    """Service for Google Reader."""
    userUri = '/reader/atom/user/%s'

    def __init__(self, email=None, password=None, source=None,
                 server='www.google.com', additional_headers=None,
                 **kwargs):
        """Set necessary parameters."""
        self.email = email
        self.client = source
        gdata.service.GDataService.__init__(self,
            email=email, password=password, service='reader', source=source,
            server=server, additional_headers=additional_headers,
            **kwargs)

    def GetSubscriptionList(self):
        """Get a list of subscriptions."""
        root = self.Get('/reader/api/0/subscription/list',
            converter=ElementTree.fromstring)

        def get_text_by_attr(elem, xpath, attr, names):
            for xpe in elem.findall(xpath):
                attr_name = xpe.get(attr)
                if attr_name in names:
                    yield { attr_name: xpe.text }

        data = []
        for elem in root.findall('list/object'):
            item = {}
            for attr in get_text_by_attr(elem, 'string', 'name',
                ('id', 'title')):
                item.update(attr)
            for catelem in elem.findall('list/object'):
                for attr in get_text_by_attr(catelem, 'string', 'name',
                    ('label', )):
                    item.update(attr)
            data.append(item)
        return data

    def AddSubscription(self, href, desc, label=None):
        """Add new subscription into the service."""
        token = self.Get('/reader/api/0/token', converter=lambda x: x)

        post_params = {
            's' : 'feed/%s' % href,
            't' : desc,
            'ac': 'subscribe',
            'T' : token,
        }

        if label:
            post_params['a'] = 'user/-/label/%s' % label

        postdata = urllib.urlencode(post_params)

        # Override Content-Type header. There is an issue #391 in
        # gdata-python-client.
        extra_headers = {
            'Content-Type': 'application/x-www-form-urlencoded',
        }

        return self.Post(postdata, '/reader/api/0/subscription/edit',
            extra_headers=extra_headers, converter=lambda x: x)

    def RemoveSubscription(self, href):
        """Unsubscribe of given subscription."""
        token = self.Get('/reader/api/0/token', converter=lambda x: x)

        post_params = {
            's' : 'feed/%s' % href,
            'ac': 'unsubscribe',
            'T' : token,
        }

        postdata = urllib.urlencode(post_params)

        # Override Content-Type header. There is an issue #391 in
        # gdata-python-client.
        extra_headers = {
            'Content-Type': 'application/x-www-form-urlencoded',
        }

        return self.Post(postdata, '/reader/api/0/subscription/edit',
            extra_headers=extra_headers, converter=lambda x: x)

class OPMLGen(object):
    """ Common class to cover all available services """
    def __init__(self):
        self.module = sys.modules[globals()['__name__']]

    def list_supported_services(self):
        """ List supported services """
        for attr in dir(self.module):
            if attr.endswith('Service') and attr != 'Service':
                yield attr.replace('Service', '')

    def get_service_by_name(self, name):
        """ Get Service object by its name """
        for srv in self.list_supported_services():
            if srv.lower() == name.lower():
                return getattr(self.module, srv + "Service")()
        raise OPMLGenError("Service '%s' doesn't support" % name)

def save_to_file(service, opts):
    """ Save items to given file """
    out = []
    out.append("<?xml version='1.0'?>")
    out.append("<opml version='1.1'><head>")
    out.append("</head><body>")
    if opts.subfolder is not None:
        out.append('<outline title="%s" text="%s">' %
                (opts.subfolder, opts.subfolder))
    if opts.sort:
        for desc, href in sorted(service.opml(opts.self),
                key=operator.itemgetter(1)):
            out.append('<outline text="%s" xmlURL="%s" />' % (desc, href))
    else:
        for desc, href in service.opml(opts.self):
            out.append('<outline text="%s" xmlURL="%s" />' % (desc, href))
    if opts.subfolder is not None:
        out.append("</outline>")
    out.append("</body></opml>")

    if opts.output == '-':
        fd = sys.stdout
    else:
        fd = open(opts.output, 'w')

    for line in out:
        fd.write("%s\n" % line.encode('utf-8'))
    fd.close()

def diff(service, opts):
    host = 'reader.google.com'
    try:
        login, _, passwd = get_auth_data(host)
    except TypeError:
        raise OPMLGenError("Can't get auth data for host '%s'" % host)

    gr = GoogleReader()
    gr.ClientLogin(login, passwd)

    old = {}
    for item in gr.GetSubscriptionList():
        if item.get('label', None) == opts.subfolder:
            href = item.get('id', '').replace('feed/', '', 1)
            old[href] = item.get('title', '')

    new = {}
    for desc, href in service.opml(opts.self):
        if href in old:
            old.pop(href, '')
        else:
            new[href] = desc

    return old, new

def main(argv):
    """ Main rountine """
    parser = OptionParser()

    parser.add_option("--service", dest="service", default="none",
            help="generate file for SERVICE")
    parser.add_option("--list", dest="list", action="store_true", default=False,
            help="list supported services")
    parser.add_option("--sort", dest="sort", action="store_true", default=False,
            help="sort output alphabetically")
    parser.add_option("--self", dest="self", action="store_true", default=False,
            help="add self feed to output")
    parser.add_option("--subfolder", dest="subfolder",
            help="put all items under given SUBFOLDER")
    parser.add_option("--diff", dest="diff", action="store_true", default=False,
            help="get difference between subscriptions of Google Reader and given service")
    parser.add_option("--output", dest="output", default="-",
            help="save output to the FILE")

    (opts, args) = parser.parse_args(argv)

    # Setup logging
    formatter = logging.Formatter("%(asctime)s %(levelname)s %(message)s",
                                  "%b %d %H:%M:%S")
    handler = logging.StreamHandler(sys.stderr)
    handler.setFormatter(formatter)
    LOG.addHandler(handler)

    # Initialize main object
    opmlgen = OPMLGen()

    # Get supported services and print them out if asked
    if opts.list:
        for srv in opmlgen.list_supported_services():
            print "\t%s" % srv
        return 0

    # Get service object
    try:
        service = opmlgen.get_service_by_name(opts.service)
    except OPMLGenError, err:
        LOG.error(str(err))
        return 1

    # Handle '--diff'
    if opts.diff:
        try:
            removed, added = diff(service, opts)
            print "Removed(%d):" % len(removed)
            for href, desc in removed.iteritems():
                print "\t%s - %s" % (href, desc)
            print
            print "Added(%d):" % len(added)
            for href, desc in added.iteritems():
                print "\t%s - %s" % (href, desc)
            return 0
        except OPMLGenError, err:
            LOG.error(str(err))
            return 1

    # Iterrate through items and write them to file
    try:
        save_to_file(service, opts)
    except OPMLGenError, err:
        LOG.error(str(err))
        return 1

    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))
